# Generated by Django 3.0.6 on 2020-05-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_type',
            new_name='digital',
        ),
    ]
